name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
      - Develop
      - Develop-f
      - Deploy
      - features/*
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         cd frontend
         npm install
      - name: Build
        run:  |
         cd frontend
         npm run build
         CI=false npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FSERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html
            rm -rf *
            scp -r ../frontend/build/* .
