name: CI/CD 

on:
  push:
    branches:
      - main
      - Develop
      - Deploy
      - feature/*
      - release/*

jobs:
  backend-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/Deploy'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: List files
      run: |
        ls -la    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run backend tests
      run: |
        pytest test.py