name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
      - Develop
      - Develop-f
      - Deploy
      - features/*
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/deploy/folder
            rm -rf *
            scp -r ../build/* .
