name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Develop
      - deploy
      - feature/*
      - release/*

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db2
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create database tables
        run: python db.py    

      - name: Run backend tests
        run: |
          pytest test.py

  deploy:
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          script: |
            cd /root/superadmin
            git pull 
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl restart app
            sudo -S systemctl restart nginx
